### ISSUE TITLE
数据丢失

### ISSUE THREAD

**Issue by MIKU-CL** [biuuu/genshin-wish-export#104]
大佬希望能加一个从头全部加载一遍的功能，我刚才使用的时候他中间漏了一个五星，但是如果只是点更新数据，它并不会对中间的数据进行检查
![B20OU$BNFW5`YW4BYFB186P](https://user-images.githubusercontent.com/36833022/148164211-cc50ed6f-211f-400f-89a3-6f03cf640c81.png)

![MA014W1WGCK8)W_`2DKWN4V](https://user-images.githubusercontent.com/36833022/148164221-ebab3c8a-32e0-4a1c-b0c1-6decc1e771f3.png)

![V0DJS)S~ )O)D9B8DR~8XQF](https://user-images.githubusercontent.com/36833022/148164293-0986e87e-d682-4c13-a830-8e7cf6703029.png)

**Comment by biuuu** [comment]
后面这张图是怎么加载的莫娜呢

**Comment by MIKU-CL** [comment]
> 

我通过导出表格并删除了表格一的部分，然后用转换js的那个网站转换了一下，然后重新放到软件里面让他从头加载了一遍

**Comment by biuuu** [comment]
添加了获取完整数据的选项
