### ISSUE TITLE
Show 4* pity counter

### ISSUE THREAD

**Issue by qhadron** [biuuu/genshin-wish-export#107]
In Genshin, 4* and 5* pity counters are tracked separately[^1]. There's currently a 5* pity counter, can you show the 4* pity counter too?

I wrote a patch[^2] ([0001-add-4-star-pity-counter.txt](https://github.com/biuuu/genshin-wish-export/files/7864949/0001-add-4-star-pity-counter.txt)) that I've been using for the past few months.
If you're interested, you can use it directly or I can make a PR.

[^1]: Some more info: if you pull 5* it does not reset 4* pity, when you pull 5* it overrides 4* pity. Basically just count 4* pity separately from 5*.
[^2]: `git am < 0001-add-4-star-pity-counter.txt` to apply the commit. I made up all the translations except English/Chinese.

**Comment by biuuu** [comment]
I don't think 4* pity counter is very necessary.
Users may only care about when 5* may be obtained.
If there is a wish details page, we can consider adding a 4* pity counter display.
