### ISSUE TITLE
能否加个隐藏新手祈愿隐藏的开关

### ISSUE THREAD

**Issue by tldzyx** [biuuu/genshin-wish-export#109]
部分玩家(比如在下)只关注当前的总体抽卡状况, 对于完结无变化的新手祈愿(固定20抽早就抽完了), 其实并不需要看, 但是每次更新后还要重新调整布局隐藏"新手祈愿"比较麻烦, 希望能加个开关保持新手祈愿的隐藏.

**Comment by biuuu** [comment]
https://github.com/biuuu/genshin-wish-export/commit/67c4617dacff1c4c5ec9f4e091ecdb4e44533317
现在可以了
