### ISSUE TITLE
增加新用户超过5个新用户会出现数据刷新错位

### ISSUE THREAD

**Issue by friends-xiaohuli** [biuuu/genshin-wish-export#119]
增加新用户超过5个新用户会出现数据刷新错位
6个角色的数据选择第4个更新数据会直接跳转到第2个数据刷新，选择第3个更新数据会直接跳转到第4个数据刷新，可以说全部错位的

**Comment by biuuu** [comment]
更新第几个数据跟选择的没有关系，
从游戏日志获取到的是哪个账号就更新哪个账号。
也就是说跟游戏里最后用来查看历史记录的账号有关系。

**Comment by friends-xiaohuli** [comment]
> 

哦，我懂了

**Comment by friends-xiaohuli** [comment]
> 

哦，我懂了

**Comment by friends-xiaohuli** [comment]
> > 
> 
> 哦，我懂了
