### ISSUE TITLE
3.0版本记录工具打开页面读不出来URL

### ISSUE THREAD

**Issue by Stllcn233** [biuuu/genshin-wish-export#132]
即便是打开也读不出来，求大大可以更新吗？

**Comment by RunawayBoat** [comment]
等适配吧，祈愿记录页面改了

**Comment by xiaojie77** [comment]
> 等适配吧，祈愿记录页面改了

作者大大留了一手，你看看设置里边有一个代理模式，打开就有了

**Comment by Exdragon25** [comment]
3.0的祈愿记录点击右上角[选项]选择[代理模式]就可以更新了, 亲测可行.

**Comment by shanyanshuo** [comment]
在你的C盘里找到C:\Users\你的用户名\AppData\LocalLow\miHoYo\原神，里面有个output.txt，记事本打开查找#/log，最后一个就是祈愿url，往前到OnGetWebViewPageError:{"url":之后一大串就是你的祈愿连接，不过最好打开游戏祈愿记录让他刷新一下

**Comment by Stllcn233** [comment]
好的&nbsp; 感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月25日(星期四) 上午10:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [biuuu/genshin-wish-export] 3.0版本记录工具打开页面读不出来URL (Issue #132)





 
在你的C盘里找到C:\Users\你的用户名\AppData\LocalLow\miHoYo\原神，里面有个output.txt，记事本打开查找#/log，最后一个就是祈愿url，往前到OnGetWebViewPageError:{"url":之后一大串就是你的祈愿连接，不过最好打开游戏祈愿记录让他刷新一下

**Comment by felaray** [comment]
國際服好像不一樣,只有個 output_log.txt 但是沒相關url..
