### ISSUE TITLE
原神3.0更新，抽卡记录界面改版，软件无法使用

### ISSUE THREAD

**Issue by xunyoyo** [biuuu/genshin-wish-export#140]
RT

**Comment by Fairytaley** [comment]
> RT

https://mp.weixin.qq.com/s/9p0izJfjiHDAmBPWmvZ-fw 微信公众号里的  我是按这个里面的改了才有用的

**Comment by ShuiYidi** [comment]
该问题在 #134 中提到了解决方案，转述如下：

> 鼠标移至右上角“选项”按钮，可以看到一个“代理模式”按钮，点击后工具会启动系统代理。
> 这时再打开游戏内的历史记录页面就能获取到数据了。
> 
> Move the mouse to the "options" button in the upper right corner to see a "Proxy mode" button. After clicking, the tool will start the system proxy.
> Then open the history page in the game to get the data.
> 
> Because the domain name of the history page has been changed to hoyoverse.com, the proxy mode cannot work temporarily.
> Expected to be fixed in v0.8.4 in a few hours.
