### ISSUE TITLE
更新到0.8.7后角色池数据丢失

### ISSUE THREAD

**Issue by f59375543** [biuuu/genshin-wish-export#152]
原本我的数据是从开服到现在，结果点击获取卡池更新后，武器池和普池都正常，角色池只剩六个月了

![20220910114318](https://user-images.githubusercontent.com/43315911/189467417-b2212d39-59b4-4fae-ae23-23252cd3236a.png)
![20220910114236](https://user-images.githubusercontent.com/43315911/189467421-968a2b9c-bcd1-4d5a-ad9a-ebd0eabbb6bc.png)

**Comment by biuuu** [comment]
上面的武器和常驻时间都不一致，可能是两个角色的记录？

**Comment by f59375543** [comment]
> 上面的武器和常驻时间都不一致，可能是两个角色的记录？

UID一致

**Comment by biuuu** [comment]
![image](https://user-images.githubusercontent.com/10892119/190170789-57885f39-0ff0-417f-98c4-aa1194b0121c.png)
你看这武器时间，下面反而比上面早了

**Comment by f59375543** [comment]
> 

估计是同步问题，我第一次抽武器池是12月

但是选择更新数据后，工具不知道为什么把他推移到9月了

**Comment by biuuu** [comment]
你手动改过json吗

**Comment by f59375543** [comment]
> 你手动改过json吗

因为我之前删过一次工具，所以我把之前导出的excl用这个转化为json然后放在新工具的userdata下

https://genshin-gacha-export.danmu9.com/

**Comment by biuuu** [comment]
excel发一份到网盘我看看

**Comment by biuuu** [comment]
这是其它工具导出的，这个网页只支持转换这边导出的excel

**Comment by f59375543** [comment]
> 这是其它工具导出的，这个网页只支持转换这边导出的excel

哦，好的，我已经不记得我当初是用哪个导出了，那我知道问题了，谢谢解答

**Comment by biuuu** [comment]
https://github.com/DGP-Studio/Snap.Hutao
你可以试试这个工具，可能支持导入这种格式的excel

**Comment by f59375543** [comment]
> https://github.com/DGP-Studio/Snap.Hutao 你可以试试这个工具，可能支持导入这种格式的excel



胡桃目前好像还不支持祈愿记录功能，作者说还在移植中

**Comment by SmallMix** [comment]
如果有保留 舊資料的json 或 Excel檔案的話可以還原  把以前的資料跟現在的資料繼續更新

舊的Excel 檔案 用這個網站轉換   https://genshin-gacha-export.danmu9.com/  
轉換成 gacha-list-"UID".json後

或是
舊的Json  不用改動 

1.先下載新版本的Genshin-Wish-Export  同步後出現userData資料夾後

2.把新的gacha-list-"UID".json 刪除掉

3.換上剛才轉換或是保留的舊的gacha-list-"UID".json

4.關掉Genshin-Wish-Export

5.開啟Genshin-Wish-Export 舊資料就會換上了 接著開遊戲中的歷史紀錄 更新數據 就會接上資料了

如果有超出80抽 90抽的情況 要進到gacha-list-"UID".json檔案 找到重複的部分  把"舊的部分"刪除掉 資料就會正常
