### ISSUE TITLE
Export data from old versions?

### ISSUE THREAD

**Issue by Nnnnn1957** [biuuu/genshin-wish-export#154]
I've been using this exporter since 2021 and I got all the wishing data from my begginers pull in an old version of it, so I was wondering if I could export all of my data to the new version of the exporter I just downloaded and how
Btw thank you for all the hard work!

**Comment by biuuu** [comment]
If there is a UserData folder under the directory of the old version, copy it to the new directory.

**Comment by Nnnnn1957** [comment]
I did it but the exporter won't open now

**Comment by biuuu** [comment]
Check whether there is any unfinished `Genshin Wish Export` process in the windows task manager. After closing, try to run the exporter in administrator mode.

**Comment by dreoxy** [comment]
Hello, I have the same problem as well. Been using this since for awhile, then noticed that it doesn't update anymore since 3.0. Updated it then tried to transfer data but couldn't get it to even open.

**Comment by biuuu** [comment]
Can you take a screenshot of the folder of this tool and send it here.
Like this:
![image](https://user-images.githubusercontent.com/10892119/189518946-578ab7ae-482b-4b6a-8161-ef4f7ee3dad8.png)

**Comment by Nnnnn1957** [comment]
> Check whether there is any unfinished `Genshin Wish Export` process in the windows task manager. After closing, try to run the exporter in administrator mode.

Did it, still won't open also here's an screenshot cause same problem as dreoxy 
![Captura de pantalla (4379)a](https://user-images.githubusercontent.com/113270146/189550713-af29465d-fbb0-48cd-963d-faaeb81374fe.png)

**Comment by dreoxy** [comment]
![321483](https://user-images.githubusercontent.com/113275785/189554802-5683dbee-2890-463a-9a36-b9d1c9c9dec7.png)

**Comment by biuuu** [comment]
Does not open mean nothing happens?
Can the old version still be opened?

https://github.com/biuuu/genshin-wish-export/releases
Try the latest version to see if it works.

**Comment by dreoxy** [comment]
> Does not open mean nothing happens? Can the old version still be opened?
> 
> https://github.com/biuuu/genshin-wish-export/releases Try the latest version to see if it works.

It works now, thanks. I do want to let you know though that there's a timeout after every 10 pages. The older version (0.6.7 I think) didn't have that so I'm not sure if that's normal.

**Comment by biuuu** [comment]
> > Does not open mean nothing happens? Can the old version still be opened?
> > https://github.com/biuuu/genshin-wish-export/releases Try the latest version to see if it works.
> 
> It works now, thanks. I do want to let you know though that there's a timeout after every 10 pages. The older version (0.6.7 I think) didn't have that so I'm not sure if that's normal.

That might be a translation issue, it actually means to wait a second

**Comment by Nnnnn1957** [comment]
It's working now, thank you so much!
