### ISSUE TITLE
User authentication expired, please reopen wish history inside the game client.

### ISSUE THREAD

**Issue by iamdevlinph** [biuuu/genshin-wish-export#156]
On version 0.8.7, I'm getting this error: `User authentication expired, please reopen wish history inside the game client.`

Already tried:
- closing and reopening the history page
- logout and login
- close the game and start again

![image](https://user-images.githubusercontent.com/19337229/190917244-47b036b0-cc7a-416c-9097-e9b0fc433fae.png)

**Comment by iamdevlinph** [comment]
Also tried with a different account and still the same results.

**Comment by biuuu** [comment]
Try to modify the log type in the settings.

**Comment by iamdevlinph** [comment]
Tried with all 3 options and still the same result.

**Comment by biuuu** [comment]
Try to turn pages on the wish history.

**Comment by iamdevlinph** [comment]
No luck. Also changed log type every time I turn the page in the history.

**Comment by biuuu** [comment]
Do you have multiple game clients on your computer?

**Comment by iamdevlinph** [comment]
Nope. Only 1. I only encountered the issue 10 hours ago.

**Comment by biuuu** [comment]
![image](https://user-images.githubusercontent.com/10892119/190942264-ed19b6b8-4130-457e-aa47-a76006282157.png)
Can you find this data_ 2 file, check its modification time?

**Comment by iamdevlinph** [comment]
Here's the file

![image](https://user-images.githubusercontent.com/19337229/190942388-53aab950-9cd4-4b84-981c-f04da89ef779.png)

I tried copying the URL directly to the "Input URL" window and got the same error.

**Comment by biuuu** [comment]
Did you copy the URL at the end of the file?

**Comment by iamdevlinph** [comment]
Yes, I copied this whole URL. From `[https://](https://webstatic-sea.hoyoverse.com/genshin/event/e20190909gacha-v2/index.html)` to `&game_biz=hk4e_global`

![image](https://user-images.githubusercontent.com/19337229/190942968-548d5a7a-3bd9-4a23-a744-7cedc60fc869.png)

**Comment by biuuu** [comment]
Does this URL work properly at https://paimon.moe/

**Comment by iamdevlinph** [comment]
![image](https://user-images.githubusercontent.com/19337229/190945080-21c89105-ed8b-4dd4-878f-cbe5cef36732.png)

It also doesn't work in paimon.moe. This URL is generated just recently. Maybe mihoyo changed their API or something.

**Comment by iamdevlinph** [comment]
Tried all the methods in paimon.moe and they also resulted to errors.

**Comment by biuuu** [comment]
It still works on my computer, but I am on the cn server, and I don't know if the global server has the same problem.

**Comment by biuuu** [comment]
I guess there is another possibility, the url in the cache file is indeed expired.
Maybe you also get the data from the cache file when you open the history page, so the url in the cache file is not updated.
A few more pages may be able to get the url that is not cached.

**Comment by iamdevlinph** [comment]
For some reason it's okay now. I closed the game for some time and tried it again just now. 🤷‍♂️

**Comment by iamdevlinph** [comment]
Also tried the Method 2 and Method 2 Alt on paimon and they work. Method 1 still doesn't work.

Will close this for now since it seems like just some rare issue.
