### ISSUE TITLE
软件是白，求Json 去excel 的手段

### ISSUE THREAD

**Issue by XAkiraJ** [biuuu/genshin-wish-export#157]
![Screenshot 2022-09-22 231707](https://user-images.githubusercontent.com/106237112/191786288-ecb3c753-2f84-4ef3-8bbd-242b178ed36c.png)
不懂出啥问题，求解。
我个人还保留Json 的文件，只是我没有手段把它导入成excel

**Comment by XAkiraJ** [comment]
[gacha-list-811311659.txt](https://github.com/biuuu/genshin-wish-export/files/9627303/gacha-list-811311659.txt)

**Comment by biuuu** [comment]
下个新版的，把txt后缀改成json。
再把改好的json文件复制到新的文件夹的 userData 文件夹里。
最后再打开工具。
