### ISSUE TITLE
导出UIGF JSON文件不合标准

### ISSUE THREAD

**Issue by CanglongCl** [biuuu/genshin-wish-export#191]
导出早期记录的UIGF JSON文件出现以下内容
```
{
    "gacha_type": 1,
    "time": "2020-12-05 18:52:26",
    "name": "以理服人",
    "item_type": "武器",
    "rank_type": "3",
    "id": 1,
    "uigf_gacha_type": "100"
},
{
    "gacha_type": 2,
    "time": "2020-12-05 18:52:26",
    "name": "鸦羽弓",
    "item_type": "武器",
    "rank_type": "3",
    "id": 2,
    "uigf_gacha_type": "100"
},
```
其中：
1. gacha_type为递增的int，而非100、200等标识祈愿类型的字符窜。
2. id为递增的int，而非字符串
敬请修正

**Comment by CanglongCl** [comment]
> 有没有原始数据发来看看

如果您是指导出的UIGF文件：

[UIGF_120052861_orgin.json.zip](https://github.com/biuuu/genshin-wish-export/files/11169709/UIGF_120052861_orgin.json.zip)

**Comment by biuuu** [comment]
是指工具目录下的userData文件夹里的json
![image](https://user-images.githubusercontent.com/10892119/230362193-bb97b090-8ec3-4e0b-b398-7fa99c66b0ea.png)

出现这种情况应该是这个里面的数据本身有问题，是否手动修改过呢？

**Comment by CanglongCl** [comment]
您好，我打包了这部分文件，uid是120052861，后附。没有动过里面的数据。不过出现错误的数据均是早期版本的数据，UIGF上介绍过这部分时间的祈愿记录没有id字段，是否与这个原因有关？
[genshin-wish-export-userData.zip](https://github.com/biuuu/genshin-wish-export/files/11179976/genshin-wish-export-userData.zip)

**Comment by biuuu** [comment]
这里的错误数据看起来是额外添加了总抽卡数和到保底之前的抽卡数。
但我翻了下早期代码也没有发现可能导致这种情况的原因。
现在你要解决只能手动删除错误的数据。
![image](https://user-images.githubusercontent.com/10892119/230701489-69319015-4d2b-411b-a9dc-65ff9fa9adad.png)
像这样多了两个数字的可以考虑直接删掉这两个数字，但后面正常数据可能有重合的部分。
可以参考时间来确定重合的部分，然后手动去掉重复的数据。

**Comment by CanglongCl** [comment]
您好，我是另一款app的开发者。我正在适配uigf导入功能。这是我一位用户的数据。如可能，希望您在导出uigf时对这两个字段强制转换为字符串，并作校验，否则导入不合uigf标准的文件可能发生不可预知的错误。感谢。

**Comment by biuuu** [comment]
> 您好，我是另一款app的开发者。我正在适配uigf导入功能。这是我一位用户的数据。如可能，希望您在导出uigf时对这两个字段强制转换为字符串，并作校验，否则导入不合uigf标准的文件可能发生不可预知的错误。感谢。

虽然可以强制转字符串，但他这个情况是数据不正确导致的。直接转字符串也没法修复错误的数据， 我稍微看了下里面已经有重复的数据了。

另外原始数据没问题的情况下这个工具导出的uigf会是正常的。
