### ISSUE TITLE
星穹鐵道抽卡紀錄?

### ISSUE THREAD

**Issue by tomylee78** [biuuu/genshin-wish-export#194]
用這家 genshin-wish-export 用習慣了，一直沒換別家的抽卡紀錄
這個月鐵道上線討論度也是盛況空前，但好像還沒有具有指標性的星穹鐵道抽卡紀錄工具
想詢問作者後續會開發適配星穹鐵道的抽卡紀錄工具嗎?

**Comment by sweetappleyf** [comment]
同求，大佬看看铁道

**Comment by lostmask2060** [comment]
支持，如果大佬有时间的话请做一个吧

**Comment by WSMTBG** [comment]
复议，大佬看看崩铁

**Comment by JM-FRANK** [comment]
agree too

**Comment by Mz-xiaofeng** [comment]
附议，希望能有崩铁的

**Comment by dozbamb** [comment]
同求，想要同款的

**Comment by XTR0411** [comment]
+1

**Comment by Infatuation-Fei** [comment]
顶一下，希望整个星穹铁道的抽卡记录分析

**Comment by a137933** [comment]
+1

**Comment by xuanluoxiaofeng** [comment]
+1

**Comment by dreamwar2005** [comment]
同求，据说API是一样的，这样的话还是更喜欢你的作品！！！

**Comment by nyano** [comment]
感谢！mark 等待更新

**Comment by SWZi66** [comment]
一把子期待住了

**Comment by SWZi66** [comment]
在做了在做了.jpg

**Comment by biuuu** [comment]
https://github.com/biuuu/star-rail-warp-export
可以试试了，但国际服还没测试过，不知道行不行

**Comment by SWZi66** [comment]
而你,我的朋友,你才是真正的英雄
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年5月1日 17:53
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [biuuu/genshin-wish-export] 星穹F道抽卡o? (Issue #194)


https://github.com/biuuu/star-rail-warp-export
可以试试了，但国际服还没测试过，不知道行不行

―

**Comment by tomylee78** [comment]
原作者開發成功囉，有需要的話請移駕這裡下載使用吧!  

[星穹鐵道抽卡工具 star-rail-warp-export](https://github.com/biuuu/star-rail-warp-export)
