### ISSUE TITLE
替换userData文件夹中的json总是失败

### ISSUE THREAD

**Issue by SerenXia** [biuuu/genshin-wish-export#199]
因为新下载了genshin-wish-export，但是提取数据之后只有近半年的数据了……
不过我有旧数据的json，所以按照genshin-wish-export的json格式把旧数据加入了json里面……
但是一按“更新数据”，这个文件就又自动被恢复成原来只有半年的那个json文件了……

想问问这个要怎么解决呀……

**Comment by biuuu** [comment]
解决了？需要重启工具

**Comment by SerenXia** [comment]
> 
其实没有解决…… 我也尝试过重启工具的。具体步骤是这样：
提取数据
（得到了近半年的数据）
替换json文件
更新数据
（发现json文件被恢复成原来那个 只有半年数据的json了）
关闭工具
重启工具
提取数据
关闭工具
替换文件
重启工具
数据没有了，又只能提取数据
（发现json文件被恢复）
关闭工具
重启工具
提取数据
替换文件
关闭并重启工具
（发现没有数据，又得）提取数据
（发现json文件又被恢复了）

我昨天晚上把这个issue close掉的主要原因是 
重复上述步骤几次，核对json格式几次都解决不了，就下了别的工具把全部的数据导入到那边看了。因为那个工具能用，就暂时本工具删了。
很奇怪的是，本工具导出的json好像是UIGF格式的，但是我无法用本工具的json文件直接导入到别的UIGF格式的工具里面……试了两个都提示是 文件中没有可识别的内容。
所以我删除本工具的文件夹的时候，没有备份本工具的json文件……等我清空回收站的时候才想起来我在这边开了一个issue……但我现在没有本工具的json文件可以复刻这个issue了…… 所以就把这个issue关了……

但其实我现在想想，alldata的json文件和近半年的json文件我都是可以重新生成的……
（我昨晚可能是失了智了吧：（

anyway…… 因为我重启本工具之后，主界面并不显示上次抓取的数据… 感觉这好像也不太对……请问有什么解决办法吗？
又或许是我抓取数据之后漏操作了吗？
