### ISSUE TITLE
3.8版本更改了cache的位置

### ISSUE THREAD

**Issue by gggssepgf** [biuuu/genshin-wish-export#206]
3.8 版本把原来的 Genshin Impact\Genshin Impact Game\YuanShen_Data\webCaches\Cache\Cache_Data
改成了 Genshin Impact\Genshin Impact Game\YuanShen_Data\webCaches\2.13.0.1\Cache\Cache_Data
2.13.0.1这个目录不知道是啥意思，把2.13.0.1目录下的cache复制到原目录就能获取记录了

**Comment by rong-xiaoli** [comment]
国际服同问
等一波更新

**Comment by zhu-ty** [comment]
等一波更新

**Comment by canyi2** [comment]
实测能用
