### ISSUE TITLE
[Bug] 4.1版本后无法导出提示url不存在

### ISSUE THREAD

**Issue by rong-xiaoli** [biuuu/genshin-wish-export#220]
提示：未找到URL，请确认是否已打开游戏抽卡记录
cookie已刷新

**Comment by sjx-github** [comment]
可以尝试更新到最新版本(0.9.1)或者手动将游戏安装目录下的YuanShen_Data\webCaches文件夹下修改日期最新的那个文件夹(我的是2.16.0.0)内的东西复制，替换或覆盖掉webCaches\Cache\Cache_Data目录下的同名文件
