### ISSUE TITLE
正在使用代理模式[172.28.112.1:8325]获取URL，请重新打开游戏抽卡记录,游戏内部打开历史记录后无任何变化

### ISSUE THREAD

**Issue by kwldx** [biuuu/genshin-wish-export#231]
游戏内部打开历史记录后无任何变化
国际服-亚服
4.2版本更新后发生
语言-繁体中文
genshin-wish-export版本0.9.7&0.9.8
![QQ截图20231112231033](https://github.com/biuuu/genshin-wish-export/assets/40017795/cf4f5df6-d201-4b3c-bdd1-146b0494f03b)

**Comment by biuuu** [comment]
设置里記錄類型选择國際服，关闭Proxy模式后试试

**Comment by kwldx** [comment]
> 设置里記錄類型选择國際服，关闭Proxy模式后试试

感谢,已解决
多次删除cache_data后,尝试成功
