### ISSUE TITLE
允许导出具有可读性的JSON文件

### ISSUE THREAD

**Issue by yudonglin** [biuuu/genshin-wish-export#234]
UI示意图
![Screenshot 2023-12-22 104727](https://github.com/biuuu/genshin-wish-export/assets/37920527/f8ce9511-6ee3-42f8-bbdf-5241130beb2a)
结果:
![image](https://github.com/biuuu/genshin-wish-export/assets/37920527/e52ae110-1e8f-4ca0-a3a1-816c4f26f248)

**Comment by yudonglin** [comment]
如果你希望我来实现这个功能，请把这个Issue指派给我

**Comment by biuuu** [comment]
checkbox可以放到按钮右边
