### ISSUE TITLE
导出时报错'EXPORT_UIGF_JSON': Error: Couldn't find the item_id for the 沐浴龙血的剑.

### ISSUE THREAD

**Issue by NiZenMeHenJiuJie** [biuuu/genshin-wish-export#253]
![QQ截图20240402221156](https://github.com/biuuu/genshin-wish-export/assets/121837802/17e59c2f-2e0f-47f7-b508-6c1e9133795f)

**Comment by chongci233** [comment]
我也遇到了同样的问题
更新0.11.6 版本后，出现Error invoking remote method 'EXPORT_UIGF_JSON': Error: Couldn't find the item_id for the 神射手之誓.

**Comment by biuuu** [comment]
现在好了没

**Comment by NiZenMeHenJiuJie** [comment]
> 现在好了没

<img width="677" alt="{E9E53762-5BAB-4022-A2D6-D06FC784B0E4}" src="https://github.com/biuuu/genshin-wish-export/assets/121837802/bc916dbe-f11f-4639-86a9-b53d42166748">

**Comment by biuuu** [comment]
https://api.uigf.org/dict/genshin/all.json
你点这个会下载吗

**Comment by NiZenMeHenJiuJie** [comment]
> https://api.uigf.org/dict/genshin/all.json 你点这个会下载吗

我把访问github修改host的工具关了后，点击这个可以下载了。再次尝试用祈愿工具，导出成功了，感谢作者大佬！

**Comment by hzp021026** [comment]
> https://api.uigf.org/dict/genshin/all.json 你点这个会下载吗

我也有上面的问题，但我点这个不会下载，清问怎么解决

**Comment by biuuu** [comment]
> > https://api.uigf.org/dict/genshin/all.json 你点这个会下载吗
> 
> 我也有上面的问题，但我点这个不会下载，清问怎么解决

有可能是这个网站本身暂时访问不了，不过我现在可以打开。
如果你现在还是打不开应该就是网络问题导致你访问不了。

你可以把这个json文件复制到工具的 userData 文件夹里，然后重新打开工具试试。
[item-id-dict.json](https://github.com/user-attachments/files/18289120/item-id-dict.json)
