### ISSUE TITLE
json 导入失败

### ISSUE THREAD

**Issue by ZQ-BB** [biuuu/genshin-wish-export#256]
[Uploading UIGF_123797971_202311122100.json…]()
之前2023年11月20左右导出的，但是现在新版本导入不了了

**Comment by KFCboy** [comment]
花了点时间查看了下代码，v2.2没有itemId,所以导入失败，我自己写个脚本请求获取下应该能解决

**Comment by biuuu** [comment]
itemId用空字符串应该也可以，再导出就会自动加上itemId了

**Comment by KFCboy** [comment]
主要是因为缺少这个字段，加空字符串和查字典加都是一样的工作量，不如作者你把兼容做一做，嘿嘿

**Comment by biuuu** [comment]
@yudonglin 这个是不是因为 JSON Schema 拦掉了

**Comment by yudonglin** [comment]
> @yudonglin 这个是不是因为 JSON Schema 拦掉了

应该是，因为从2.3开始，item_id是强制的:

> In UIGF standard v2.3, we prioritize item_id and make it as a required field. This allows UIGF data set to support multi-language environment that common seen in international server, and allows worldwide Genshin-related software been connected together.
在统一可交换祈愿记录标准2.3版本中，我们将item_id的优先度提高，成为必填的字段。 这将允许 UIGF / SRGF 标准支持国际服的多语言环境，进而将更多的原神工具连接在一起。

所以在src/main/UIGFJson.js里
`
validateUigfJson(importData)
`
不会通过。

可以考虑在validateUigfJson(importData)触发之前做一些兼容工作，比如根据name自动填入item_id，如果你想我来搞一下也可以
