### ISSUE TITLE
舊版祈願紀錄xslx轉json還是導入失敗，有甚麼辦法嗎? (看了 read me 以後，userdata舊文件刪掉，放入下載的文件，重啟程式重新讀就好了

### ISSUE THREAD

**Issue by sasmwh** [biuuu/genshin-wish-export#259]
(更新)

看了readme 之後，把 userdata舊文件刪掉，放入下載的文件，重開程式重新讀取就好了

舊版祈願紀錄20220516的還是excel的xslx
xslx轉json還是導入失敗
，有甚麼辦法嗎?
有附上我的舊紀錄，
求求各位大佬幫忙
![Desktop Screenshot 2024 04 29 - 17 12 29 02](https://github.com/biuuu/genshin-wish-export/assets/56946282/1843458b-5083-4bed-8e33-1df48c3aed20)
[gacha-list-825241113.json](https://github.com/biuuu/genshin-wish-export/files/15147142/gacha-list-825241113.json)

**Comment by yudonglin** [comment]
我知道为什么了，我的锅... 正在修复中...
