### ISSUE TITLE
绝区零

### ISSUE THREAD

**Issue by swlkkk** [biuuu/genshin-wish-export#264]
大佬能做个绝区零得抽卡记录吗

**Comment by earthjasonlin** [comment]
暂时魔改了一个绝区零的 [earthjasonlin/zzz-signal-search-export](https://github.com/earthjasonlin/zzz-signal-search-export)，期待[大佬说的三合一](https://github.com/biuuu/star-rail-warp-export/issues/68#issuecomment-2208200279)

**Comment by LostWarriorFamg** [comment]
> 暂时魔改了一个绝区零的 [earthjasonlin/zzz-signal-search-export](https://github.com/earthjasonlin/zzz-signal-search-export)，期待[大佬说的三合一](https://github.com/biuuu/star-rail-warp-export/issues/68#issuecomment-2208200279)

试了下身份认证不了，一直提示过期，清理缓存还是没办法用😂代餐吃不了了
