### ISSUE TITLE
数据有重复错乱

### ISSUE THREAD

**Issue by alone-art** [biuuu/genshin-wish-export#271]
![1722941297391](https://github.com/user-attachments/assets/1a0046c6-64c3-4679-94dc-20990b7cd5ed)
今天软件内更新程序后查抽卡记录, 发现选中部分是重复了的, 中间迪卢克隔开。不确定是更新前就是这样还是更新后是这样，之前也有查抽卡记录，但是没注意有没有重复。

**Comment by alone-art** [comment]
第一个芙宁娜是68， 迪卢克后面的芙宁娜是75，但查看两个时间是一样的。

**Comment by biuuu** [comment]
是什么服务器的

**Comment by alone-art** [comment]
> 是什么服务器的

国服

**Comment by biuuu** [comment]
暂时没发现原因，有可能是之前数据就有问题。你只能手动改一下 userData目录里的json文件，删掉重复的数据。
改了之后要重启工具才会生效。
