### ISSUE TITLE
[v0.5.0 - v0.5.3]Data mege BUG, 数据合并BUG

### ISSUE THREAD

**Issue by biuuu** [biuuu/genshin-wish-export#36]
v0.5.0 - v0.5.3 存在BUG，可能导致更新数据后，缺失某一段记录，
进而在自动更新升级到后续版本后，合并数据时出现重复的数据。
如果出现这种情况请更新至 v0.5.4以上的版本，并删除工具目录下的 userData 文件夹，重新加载数据。

V0.5.0-v0.5.3 has a BUG that may cause a record to be missing after the data has been updated,
this in turn causes duplicate data to be merged after an automatic update to a later version.
If this happens, update to v0.5.4 or higher and delete the userData folder in the tools directory to reload the data.

**Comment by nowstarfall** [comment]
好耶！我还以为是我电脑问题
