### ISSUE TITLE
原神官方只能查询 6 个月的记录吧，是否可以考虑做一些数据持久化的功能

### ISSUE THREAD

**Issue by HaloWang** [biuuu/genshin-wish-export#38]
- 从 excel 中导入数据？
- localStorage？

还是说已经有这个功能了，不过我并没有在 readme 中看到？

**Comment by Redlnn** [comment]
本地数据存放在`Genshin-Gacha-Export\userData`中

**Comment by Swift-Lee** [comment]
> 本地数据存放在`Genshin-Gacha-Export\userData`中

要是能有备份功能就好了，比如备份到自己的私有仓库，或者云盘什么的

**Comment by TheTychoStar** [comment]
> > 本地数据存放在`Genshin-Gacha-Export\userData`中
> 
> 要是能有备份功能就好了，比如备份到自己的私有仓库，或者云盘什么的

你把userData下面对应账号的json文件备份出来就行了呀。
