### ISSUE TITLE
更改语言后一些条目没有变化

### ISSUE THREAD

**Issue by wh7** [biuuu/genshin-wish-export#40]
1. 不同的祈愿标题没有随语言改变，比如「常驻祈愿」、「角色活动祈愿」等
2. 祈愿获得的物品的名称，比如游戏在中文界面下导出的是「武器」——「风鹰剑」，不会随着程序语言变化而改变。

（对于2，要实现的话也许需要准备一个多语种的物品名称对应表，而且需要随着版本更新而不断补充，可能比较麻烦。目前简单的一个办法是改变游戏显示语言，重新导出。）

![ca](https://user-images.githubusercontent.com/45503569/110565848-1a33bb80-818a-11eb-9d2c-0be5229f6374.png)

**Comment by biuuu** [comment]
这个是游戏语言决定的，重新导出会受到6个月记录的限制。
但对于普通用户来说这不是问题，切换语言功能只是为了防止自动获取系统语言失败做的一个备选方案。
实际上用户是不需要看这些条目有没有在手动切换语言时有没有变化的。

**Comment by wh7** [comment]
恩，我考虑的是特殊的使用情况，比如是需要和外国友人比较欧气的时候。的确这种时候改变游戏语言就可以了。
