### ISSUE TITLE
BUG抽卡记录读取错误0.5.6

### ISSUE THREAD

**Issue by Klamist** [biuuu/genshin-wish-export#41]
https://sm.ms/image/SXLgwZTDFI6HUE2
号主表示只用了0.5.6版本，然后按说明操作，读出来的就有问题……
124的胡桃应该是52，护摩应该是68……
B站一个人找我的，他空间：https://space.bilibili.com/1634380

**Comment by biuuu** [comment]
工具会自动更新，他看到的0.5.6可能是自动更新的。
只要0.5.3时加载过数据都有可能出现问题。
如果清数据后还能复现这个问题，那就是有BUG。

**Comment by biuuu** [comment]
我现在看到图片了，从图标可以看出他的工具确实是从老版本自动更新上来的。
很可能在0.5.0-0.5.3之间更新过抽卡数据。
清空 userData 文件夹再试吧。

**Comment by Klamist** [comment]
似乎没问题了。抱歉打扰了……
