### ISSUE TITLE
2021/03/17 Genshin Impact 1.4 - Wish history API changed

### ISSUE THREAD

**Issue by biuuu** [biuuu/genshin-wish-export#53]
The tool will get unlimited data, which needs to be resolved after updating to v0.6.3.
If the data is inconsistent with the game, delete the `userData` folder in the tool directory, restart the tool and then load the data.

**Comment by GuryYu** [comment]
v0.6.3, getData.js, Line 266, getQuerystring Method.
before return searchParams, needs to add "searchParams.delete('end_id')".

**Comment by biuuu** [comment]
@GuryYu 
The URL currently retrieved from the log does not appear to have an end_id parameter. 
The current version should work just fine.
However, this line of code is much more complete. 
Would you like to send a pull request.

**Comment by rnadow** [comment]
原来如此，今天突然发现
