### ISSUE TITLE
统计错误，半部讨龙统计丢了（再非也不嫩温迪159发）

### ISSUE THREAD

**Issue by WXZhao7** [biuuu/genshin-wish-export#54]
有个莫娜的没有识别出来，删除5.15重装6的，两次都是识别为这样
![image](https://user-images.githubusercontent.com/56864878/111419121-d7db2300-8723-11eb-93ec-314a157b12cb.png)

**Comment by biuuu** [comment]
等0.6.2吧

**Comment by biuuu** [comment]
下载新版可以解决，
自动升级的话，删掉 `userData` 文件夹再打开工具。
