### ISSUE TITLE
v0.6.5 数据异常

### ISSUE THREAD

**Issue by JDYuuki** [biuuu/genshin-wish-export#59]
翻 JSON 可以发现，每个池子（除了新手池），都莫名多了40条不正确的记录：
![image](https://user-images.githubusercontent.com/28827378/112037381-a5df1c00-8b7c-11eb-8084-78d5f788c761.png)
~这些异常的记录格式和正常数据不一样~ 发现是新版本更换了 JSON 格式
 
手动删除这些记录后，下次点击更新又会出现这40条异常记录。
 
至于是怎么发现的，主要是我有手动记录的习惯……
![image](https://user-images.githubusercontent.com/28827378/112038071-6107b500-8b7d-11eb-8c13-6390f8ef2f9a.png)
![image](https://user-images.githubusercontent.com/28827378/112038148-78df3900-8b7d-11eb-947a-6b44da1dba54.png)

**Comment by JDYuuki** [comment]
刚刚备份了旧的JSON后重新拉了一遍数据，发现这是新的数据格式 XD
 
我尝试了下从旧的JSON将已经超过6个月的数据导入进去的时候，如果不手动将旧的数据改成新的数据格式，则会被自动删除。
在我手动将超时抓取不到的数据导入进去后才能被正常识别而不被删除
![image](https://user-images.githubusercontent.com/28827378/112039615-31f24300-8b7f-11eb-8d4a-273a0f2c3f37.png)
![image](https://user-images.githubusercontent.com/28827378/112039788-649c3b80-8b7f-11eb-932f-19a4fb0cc6b2.png)

**Comment by biuuu** [comment]
翻了下代码，确实从一开始就没有这种格式……

**Comment by JDYuuki** [comment]
> 翻了下代码，确实从一开始就没有这种格式……

啊这，那就很神奇了，这JSON是哪来的……

**Comment by Klamist** [comment]
> > 翻了下代码，确实从一开始就没有这种格式……
> 
> 啊这，那就很神奇了，这JSON是哪来的……

github与NGA传过好几类导出软件。你这个看似另一个软件的导出json，反正不是这个项目的。
