### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by SGodV** [biuuu/genshin-wish-export#60]
一开始是更新数据卡住
后来就下面这样了
![image](https://user-images.githubusercontent.com/37214323/112264299-a3c7ab00-8cab-11eb-8826-98f33be617c2.png)

**Comment by SGodV** [comment]
重下也没法解决

**Comment by biuuu** [comment]
不用放原神文件夹，这样应用程序反而没有权限操作当前路径。
