### ISSUE TITLE
能不能加个根据时间排序或者去重的

### ISSUE THREAD

**Issue by phytha** [biuuu/genshin-wish-export#61]
能不能加个根据时间排序或者去重的，这几次用都会出现重复计算数据的情况，以至于显示次数远远大于实际次数。
![QQ截图20210324191859](https://user-images.githubusercontent.com/57856387/112302229-cec6f480-8cd5-11eb-893f-db502ab6c698.jpg)
![QQ图片20210324191746](https://user-images.githubusercontent.com/57856387/112302236-d090b800-8cd5-11eb-9ab3-2f9fcb381a66.png)

**Comment by biuuu** [comment]
数据有问题可能是之前有BUG的版本中更新过记录。
清一下userData文件夹会正常，不过2020年9月份的数据已经开始陆续获取不到了。
要保留旧数据的话，你可能要手动截掉json文件里重复的部分数据。

**Comment by phytha** [comment]
> 数据有问题可能是之前有BUG的版本中更新过记录。
> 清一下userData文件夹会正常，不过2020年9月份的数据已经开始陆续获取不到了。
> 要保留旧数据的话，你可能要手动截掉json文件里重复的部分数据。

我是用的0.6.1版本获取的。我出现bug以后，将整个文件夹删除，再重新从压缩包里解压缩使用，也会偶尔出现这个问题。现在改成0.6.5版本，好像又好了……

**Comment by biuuu** [comment]
0.6.1就是有bug的。
