### ISSUE TITLE
部分导出记录重复

### ISSUE THREAD

**Issue by GGAutomaton** [biuuu/genshin-wish-export#70]
更新记录后发现导出记录重复。
![界面](https://user-images.githubusercontent.com/32899400/116772858-53025980-aa84-11eb-8b84-af9f99b7c239.PNG)

所有池子全部发生异常。
以常驻祈愿为例，发现原来的记录右侧，多出现了一次总次数和保底。而新出现的重复记录并没有。
![常驻](https://user-images.githubusercontent.com/32899400/116773017-737ee380-aa85-11eb-9d77-47b7e2f8a26c.PNG)

查看 gacha-list-UID.json
老记录：
![旧](https://user-images.githubusercontent.com/32899400/116773111-0b7ccd00-aa86-11eb-8904-660b661c9833.PNG)
重复的新记录：
![新](https://user-images.githubusercontent.com/32899400/116773156-53035900-aa86-11eb-9a90-feee4d395180.PNG)
可以发现所有的老记录在表示星级的3和4下面多出了数字，并且就是“总次数”和“保底内”。

这个问题和 issues 66 应该是相同的，希望尽快修复。

**Comment by biuuu** [comment]
从commit记录可以看到，这个工具一开始就没有导出那些额外数字的功能。
很有可能你用了其他工具导出的json文件。
清空本地的json文件重新导出就不会重复了。

**Comment by GGAutomaton** [comment]
经验证，先导出excel，再更新数据，就会触发这个bug。
盲猜与[excel.js的第45行和第51行](https://github.com/biuuu/genshin-wish-export/blob/main/src/main/excel.js#L45)有关。

**Comment by biuuu** [comment]
> 经验证，先导出excel，再更新数据，就会触发这个bug。
> 盲猜与[excel.js的第45行和第51行](https://github.com/biuuu/genshin-wish-export/blob/main/src/main/excel.js#L45)有关。

确实有这个问题，待我更新下。
