### ISSUE TITLE
[Windows] 当可执行文件名为 electron.exe 时应用无法启动

### ISSUE THREAD

**Issue by chenjunyu19** [biuuu/genshin-wish-export#74]
如题，当可执行文件名为 `electron.exe` 时，应用启动后空白无内容，并自动开启 DevTools。附演示视频。

应用本体版本：`0.6.9`（`2b603.zip`）

> 题外话：只是强迫症想用最新版 Electron，没有什么特别的目的。

https://user-images.githubusercontent.com/15167799/118359429-f5a6f600-b5b5-11eb-9d12-d40828f7b1d0.mp4

**Comment by biuuu** [comment]
可能因为这样是被当成了开发模式，所以无法正常运行。

**Comment by chenjunyu19** [comment]
确实如此。

<https://github.com/biuuu/genshin-wish-export/blob/46a0dea7d6f23248c7d98572ecefd47b319e7b53/src/main/main.js#L10-L24>

<https://github.com/electron/electron/blob/c68c65f383f7b210c2ad93715dd70dbb9dcb4798/lib/browser/api/app.ts#L58-L64>
