### ISSUE TITLE
数据采集出现重复

### ISSUE THREAD

**Issue by Raiden-1** [biuuu/genshin-wish-export#75]
[原神祈愿记录_20210518_170901.xlsx](https://github.com/biuuu/genshin-wish-export/files/6501029/_20210518_170901.xlsx)
[原神祈愿记录_20210518_192908.xlsx](https://github.com/biuuu/genshin-wish-export/files/6501030/_20210518_192908.xlsx)
![image](https://user-images.githubusercontent.com/75219287/118646250-87ab3a80-b812-11eb-910f-6b108caa459f.png)
和66楼情况一样，三个池子均被重复记录。20210518_170901这个文件还是正常的，18:00抽完优菈池子再导出，20210518_192908这个就出bug了，优菈出现了显示111发出。角色池的265-296行、武器池的210-249行、常驻池的137-164行均为重复。且恰好在重复之前的所有行都多了G和H两列，复制了E“总次数”和F“保底内两页”。

**Comment by biuuu** [comment]
旧版本导致的BUG，试试新加的从Excel恢复数据。可以截掉重复数据后再更新数据。
## 从 Excel 恢复数据
https://genshin-gacha-export.danmu9.com

可以通过这个网页从 Excel 文件导出 JSON 数据，也可以在网页上选择截止时间来去除重复数据。

将下载的JSON文件复制到工具的 userData 文件夹即可恢复数据。

使用网页时一定要确保填写正确的 UID， 选择正确的 Excel 文件里使用的语言。
