### ISSUE TITLE
Import data got doubled result

### ISSUE THREAD

**Issue by MacGWik** [biuuu/genshin-wish-export#77]
at 2021-05-29 night, I was trying to load data from my account (as usual, opening the history page in the game and load the data using the button)

suddenly I got 40-ish data added to my history and when I export data, it got added more columns that it should have like this
![image](https://user-images.githubusercontent.com/12266489/120088619-bbdd0000-c11c-11eb-9dd7-aa47f2a697aa.png)

 maybe you can check the code ? I'm not really experienced with electron but I can give you my excel export and try to search this date `2021-05-29 06:51:02` on the `character event wish`. It has 2 data with identical

[Genshin wish logger_20210530_082420.xlsx](https://github.com/biuuu/genshin-wish-export/files/6565540/Genshin.wish.logger_20210530_082420.xlsx)

and this is my json after trying to get more data and got this duplicate result 
[gacha-list-803730162.zip](https://github.com/biuuu/genshin-wish-export/files/6565541/gacha-list-803730162.zip)

**Comment by MacGWik** [comment]
Hhmm, after trying to figuring difference between old version json (0.6.3) with the latest one (0.6.9) I guess I knew the issue

json format is changed between the version and it cause the program behave really weird (like getting 40 ish duplicate data)

I'm sorry for reporting this bugs

**Comment by Julienraptor01** [comment]
I had the same bug i completly reformated and cleared my json in base of my Excel exporte and i don't have the problem anymore
