### ISSUE TITLE
读取json的url中的“id”如何处理

### ISSUE THREAD

**Issue by 1651515568** [biuuu/genshin-wish-export#79]
我想用py自己写一个工具，但是在如何读取下一页上遇到了难点，我不知道如何连续读取下一页，应为url上的‘id’我无法解析规律，还是说我的思路错了，萌新一个，大佬指点一下

**Comment by biuuu** [comment]
https://github.com/sunfkny/genshin-gacha-export
python可以看看这个项目的代码
