### ISSUE TITLE
请问数据可以对接paimon.moe吗？

### ISSUE THREAD

**Issue by Arondight** [biuuu/genshin-wish-export#82]
因为游戏内只保存半年前的抽卡记录，目前我所有的抽卡记录都保存在此项目里了，我想把此项目的数据放到[paimon.moe](https://paimon.moe/wish)，请问有什么办法吗？

**Comment by biuuu** [comment]
https://bbs.nga.cn/read.php?tid=27341270

**Comment by Arondight** [comment]
弄好了，谢谢。

如果有后来者看到这个Issue，直接去NGA 拷贝代码，改改打开的文件路径，本地跑一下就行，注意下面两点。

1. 此项目导出的Excel 为xlsx，需要另存为xls 才能用Python 代码处理
2. Python 代码处理后的Excel 为xls，需要另存为xlsx 才能导入paimon.moe（选择TakaGG）

**Comment by ideepblue** [comment]
> 弄好了，谢谢。
> 
> 如果有后来者看到这个Issue，直接去NGA 拷贝代码，改改打开的文件路径，本地跑一下就行，注意下面两点。
> 
> 1. 此项目导出的Excel 为xlsx，需要另存为xls 才能用Python 代码处理
> 2. Python 代码处理后的Excel 为xls，需要另存为xlsx 才能导入paimon.moe（选择TakaGG）

NGA 帖子被关闭了，不知道还有保存下的 python 脚本吗？
