### ISSUE TITLE
electron的自动更新是怎么实现的？

### ISSUE THREAD

**Issue by Helary** [biuuu/genshin-wish-export#83]
自己有在写vue打包成的一个electron程序，但是在更新这里查了好多资料，有用github更新的也有用服务器更新的，我试图用本地更新但是搜到的都是  地址:端口号/文件名 这个形式，也没有看到有解释，然后考虑用github来做更新，照着文档配置但是是失败了，看大大这里有设置127.0.0.1，那大大的electron更新文件是放在本地吗？

**Comment by biuuu** [comment]
不打包成asar，直接下载新的js源码替换。

**Comment by Helary** [comment]
大大是用的内置的更新程序还是electron-builder的electron-updater ？感谢大大

**Comment by biuuu** [comment]
自己随便写的

**Comment by Helary** [comment]
大大真的很厉害啊，谢谢大大回答我，我自己用electron-builder弄github的自动更新成功了
