### ISSUE TITLE
能否加入直接输入链接导入祈愿记录

### ISSUE THREAD

**Issue by Raiden-1** [biuuu/genshin-wish-export#85]
我一直是移动端玩家（玩3D游戏用不惯键鼠），一直更新着原神PC版就是为了用这个祈愿记录。出稻妻地图之后电脑实在装不下了，能不能加入直接输入（移动端断网刷新得到的）链接导入祈愿记录？谢谢

**Comment by biuuu** [comment]
鼠标悬停在选项上，可以看到有个输入URL按钮
