### ISSUE TITLE
查询过程出现问题

### ISSUE THREAD

**Issue by kebeo23** [biuuu/genshin-wish-export#86]
在按照正确步骤操作之后，点击更新数据，结果在查询新手祈愿的时候就不能继续了，一直卡在查询新手祈愿那里。

**Comment by biuuu** [comment]
在游戏里的抽卡记录，新手祈愿里有数据吗

**Comment by kingJinjl** [comment]
![image](https://user-images.githubusercontent.com/89332623/130344681-fe09ca69-8402-470f-b453-c4575cf7060f.png)  我也发现这个问题 一直查询不了
