### ISSUE TITLE
Not working on 2.0 patch

### ISSUE THREAD

**Issue by Heiro78** [biuuu/genshin-wish-export#87]
I have this error when going about things normal.

"Unable to find URL, please make sure you already opened wish history inside the game client - Oops, something failed"

and when using the proxy server

"Using proxy mode [192.168.254.27:8325] to get URL，please open wish history or try to refresh"

Even though I'm at the wish history screen and refresh while there too

**Comment by biuuu** [comment]
Try to change the log type in settings to "Global server".

**Comment by Heiro78** [comment]
I had that already set to global thinking it would be best. I'm running the .exe as admin

**Comment by Heiro78** [comment]
Seems my problem was not running it as admin

**Comment by Heiro78** [comment]
Thank you Biuuu!
