### ISSUE TITLE
11月2日服务器抽卡记录错乱后，将常驻池最近9月10月11月抽卡记录统计了两次

### ISSUE THREAD

**Issue by yang547473053** [biuuu/genshin-wish-export#91]
求能下次更新的时候重新加载对照以往记录多一点，把我这个更新的错误数据给刷下去，要不然看着统计了两次的9月22日常驻池琴贼难受

**Comment by biuuu** [comment]
用简介里那个网页导入Excel可以裁掉错误的日期，然后重新加载
